spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ismaeldominguezmoreno@gmail.com
    password:  sijwylzzozdgmuat
    properties:
      mail:
        smtp:
          starttls:
           enable: true
           required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/mundobancario?serverTimezone=UTC
    username: root
    password: 1234  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
management:
  endpoints:
    web:
      exposure:
        include: refresh,actuator,health,metrics
        
